"""empty message

Revision ID: 00819ea12d3f
Revises: ca211b220450
Create Date: 2021-09-29 20:17:11.177595

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00819ea12d3f'
down_revision = 'ca211b220450'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('todos', 'list_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('todos', 'list_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
